#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l pmem=7GB
#PBS -l walltime=0:10:00
#PBS -q pace-ice
#PBS -N helloexample
#PBS -o stdout
#PBS -e stderr
cd $PBS_O_WORKDIR

#module load anaconda3/4.2.0;source activate atm
ulimit -s unlimited

export MV2_ENABLE_AFFINITY=1
export MV2_CPU_BINDING_POLICY=bunch

# mpirun -np $PBS_NP ~/bin/sparc -name sprc-calc > sprc-calc.log

echo "Hello! This is an example PBS file!"

